### ISSUE TITLE
Create shortcut for creating the name of a file in the editor

### ISSUE THREAD

**Issue by JimHokanson** [JimHokanson/matlab_standard_library#37]
Often code is placed a few levels deep in packages. Via some method, perhaps to start a simple function call, we should examine the currently active file and create the function name (with packages) for the current function.

e..g in a file test.m, located in asdfasfdsadf\+a\+b\+c\test.m we should type a function like:
sl.?????.getCurrentFunctionName()
and get out:
a.b.c.test

**Comment by GregGoldman** [comment]
Started issue. Need to finish code for line 70 of sl.obj.file_path_info for when there are no packages.

**Comment by GregGoldman** [comment]
Completed issue

**Comment by JimHokanson** [comment]
Feel free to close it next time.
