### ISSUE TITLE
Add gzoom to global_namespace_functions

### ISSUE THREAD

**Issue by GregGoldman** [JimHokanson/matlab_standard_library#48]
There is a great function for extending axes of a graph so nothing gets plotted on the edges. See http://pundit.pratt.duke.edu/wiki/MATLAB:Plotting and scroll down to the gzoom section. I'd like to add it with Jim's approval.

**Comment by JimHokanson** [comment]
This would be fine somewhere in sl.plot with an appropriate name change. I don't think it is a good fit for the global namespace since I wouldn't use it during debugging.

**Comment by JimHokanson** [comment]
I ended up having a use case for this just now and copied it to sl.plot.postp.scaleAxisLimits
